version: '3'
services:

    mongodb:
      image : mongo
      container_name: mongodb
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - database:/data/db

    nginx:
      image: nginx
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend
      restart: unless-stopped

    website:
      image: website
      container_name: website
      build: ../website

    backend:
      image: backend
      container_name: backend
      build: ../backend
      ports:
        - 5000:5000
      restart: on-failure
  volumes:
  database:
