version: '3'
services:

  mongo:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tensor43v3r
    volumes:
      - database:/data/db
    ports:
      - 27017:27017

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - website
    restart: unless-stopped

  website:
    image: website
    container_name: website
    build: ../website
    restart: on-failure

  backend:
    image: backend
    container_name: backend
    build: ../backend
    # depends_on:
    #   - mongo
    ports:
      - 5000:5000
    restart: on-failure
volumes:
  database:
